language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
test:
  - npm run lint
deploy:
  provider: script
  script_cleanup: true
  script:
    - npx semantic-release
