language: node_js
notifications:
  email: false
node_js:
  - '9'
test:
  - npm run lint
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
